default: &default
  adapter: postgresql
  encoding: unicode
  username: PostgreSQL15
  password: 1234
  host: localhost
  pool: 5

development:
  <<: *default
  database: crudruby

test:
  <<: *default
  database: crudruby

production:
  <<: *default
  database: crudruby
  username: PostgreSQL15
  password: 1234
