default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  host: localhost
  database: Northwind
  pool: 5


development:
  <<: *default
  database: Northwind  

test:
  <<: *default
  database: Northwind  

production:
  <<: *default
  database: Northwind  
  username: postgres
  password: 1234
