default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  host: localhost
  database: Northwind
  pool: 5


development:
  <<: *default
  database: Northwind  # Cambia el nombre de la base de datos a "northwind"

test:
  <<: *default
  database: Northwind  # Cambia el nombre de la base de datos a "northwind"

production:
  <<: *default
  database: Northwind  # Cambia el nombre de la base de datos a "northwind"
  username: postgres
  password: 1234
